/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package at.srfg;

import at.srfg.chasi.ChasiDevice;
import at.srfg.chasi.ChasiListener;

/**
 *
 * @author dglachs, mschmoig
 */
public class MainChasiDevice extends javax.swing.JFrame {

    private ChasiDevice chasi;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToggleButton jToggleButtonRegistration;
    private javax.swing.JToggleButton jToggleButtonComponent;
    private javax.swing.JToggleButton jToggleButtonChasi;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JTree jTree1;

    private javax.swing.JLabel jLabelLinearPositionX;
    private javax.swing.JLabel jLabelLinearPositionY;
    private javax.swing.JLabel jLabelLinearPositionZ;
    private javax.swing.JLabel jLabelAngularPositionX;
    private javax.swing.JLabel jLabelAngularPositionY;
    private javax.swing.JLabel jLabelAngularPositionZ;

    private javax.swing.JTextField jTextFieldLinearPositionX;
    private javax.swing.JTextField jTextFieldLinearPositionY;
    private javax.swing.JTextField jTextFieldLinearPositionZ;
    private javax.swing.JTextField jTextFieldAngularPositionX;
    private javax.swing.JTextField jTextFieldAngularPositionY;
    private javax.swing.JTextField jTextFieldAngularPositionZ;
    // End of variables declaration//GEN-END:variables

    /*********************************************************************************************************
     * ChasiDisplay: Creates new form NewJFrame
     ********************************************************************************************************/
    public MainChasiDevice() {
        initComponents();
        chasi = new ChasiDevice();
        ChasiListener listener = new ChasiListener() {

            @Override
            public void linear_posX_Changed() {
                jTextFieldLinearPositionX.setText("" + chasi.getLinearPositionX()); }

            @Override
            public void linear_posY_Changed() {
                jTextFieldLinearPositionY.setText("" + chasi.getLinearPositionY());
            }

            @Override
            public void linear_posZ_Changed() {
                jTextFieldLinearPositionZ.setText("" + chasi.getLinearPositionZ());
            }

            @Override
            public void angular_posX_Changed() {
                jTextFieldAngularPositionX.setText("" + chasi.getAngularPositionX()); }

            @Override
            public void angular_posY_Changed() {
                jTextFieldAngularPositionY.setText("" + chasi.getAngularPositionY());
            }

            @Override
            public void angular_posZ_Changed() {
                jTextFieldAngularPositionZ.setText("" + chasi.getAngularPositionZ());
            }

        };
        chasi.setListener(listener);
    }


    /*********************************************************************************************************
     * initComponents
     *
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     ********************************************************************************************************/
    @SuppressWarnings("unchecked")
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();
        jToolBar1 = new javax.swing.JToolBar();
        jToggleButtonRegistration = new javax.swing.JToggleButton();
        jToggleButtonChasi = new javax.swing.JToggleButton();
        jToggleButtonComponent = new javax.swing.JToggleButton();
        jPanel1 = new javax.swing.JPanel();

        jLabelLinearPositionX = new javax.swing.JLabel();
        jLabelLinearPositionY = new javax.swing.JLabel();
        jLabelLinearPositionZ = new javax.swing.JLabel();
        jLabelAngularPositionX = new javax.swing.JLabel();
        jLabelAngularPositionY = new javax.swing.JLabel();
        jLabelAngularPositionZ = new javax.swing.JLabel();

        jTextFieldLinearPositionX = new javax.swing.JTextField();
        jTextFieldLinearPositionY = new javax.swing.JTextField();
        jTextFieldLinearPositionZ = new javax.swing.JTextField();
        jTextFieldAngularPositionX = new javax.swing.JTextField();
        jTextFieldAngularPositionY = new javax.swing.JTextField();
        jTextFieldAngularPositionZ = new javax.swing.JTextField();

        jScrollPane1.setViewportView(jTree1);
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        jToolBar1.setRollover(true);

        jToggleButtonComponent.setText("I4.0 Component");
        jToggleButtonComponent.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jToggleButton1ItemStateChanged(evt);
            }
        });
        jToolBar1.add(jToggleButtonComponent);

        jToggleButtonRegistration.setText("Register ARTI Chasi");
        jToggleButtonRegistration.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jToggleButton0ItemStateChanged(evt);
            }
        });
        jToolBar1.add(jToggleButtonRegistration);

        jToggleButtonChasi.setText("Start ARTI Chasi");
        jToggleButtonChasi.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jToggleButton2ItemStateChanged(evt);
            }
        });
        jToggleButtonChasi.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jToggleButton2StateChanged(evt);
            }
        });
        jToggleButtonChasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });
        jToolBar1.add(jToggleButtonChasi);

        // assign text to all labels
        jLabelLinearPositionX.setText("Linear Position X");
        jLabelLinearPositionY.setText("Linear Position Y");
        jLabelLinearPositionZ.setText("Linear Position Z");
        jLabelAngularPositionX.setText("Angular Position X");
        jLabelAngularPositionY.setText("Angular Position Y");
        jLabelAngularPositionZ.setText("Angular Position Z");

        jTextFieldLinearPositionX.setText("linear_posX");
        jTextFieldLinearPositionX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldLinearPositionXActionPerformed(evt);
            }
        });

        jTextFieldLinearPositionY.setText("linear_posY");
        jTextFieldLinearPositionZ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldLinearPositionYActionPerformed(evt);
            }
        });

        jTextFieldLinearPositionZ.setText("linear_posZ");
        jTextFieldLinearPositionZ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldLinearPositionZActionPerformed(evt);
            }
        });

        jTextFieldAngularPositionX.setText("angular_posX");
        jTextFieldAngularPositionX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldAngularPositionXActionPerformed(evt);
            }
        });

        jTextFieldAngularPositionY.setText("angular_posY");
        jTextFieldAngularPositionY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldAngularPositionYActionPerformed(evt);
            }
        });

        jTextFieldAngularPositionZ.setText("angular_posZ");
        jTextFieldAngularPositionZ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldAngularPositionZActionPerformed(evt);
            }
        });



        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabelLinearPositionX)
                                        .addComponent(jLabelLinearPositionY)
                                        .addComponent(jLabelLinearPositionZ)
                                        .addComponent(jLabelAngularPositionX)
                                        .addComponent(jLabelAngularPositionY)
                                        .addComponent(jLabelAngularPositionZ))
                                .addGap(58, 58, 58)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jTextFieldLinearPositionX)
                                        .addComponent(jTextFieldLinearPositionY)
                                        .addComponent(jTextFieldLinearPositionZ)
                                        .addComponent(jTextFieldAngularPositionX)
                                        .addComponent(jTextFieldAngularPositionY)
                                        .addComponent(jTextFieldAngularPositionZ, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabelLinearPositionX)
                                        .addComponent(jTextFieldLinearPositionX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabelLinearPositionY)
                                        .addComponent(jTextFieldLinearPositionY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabelLinearPositionZ)
                                        .addComponent(jTextFieldLinearPositionZ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabelAngularPositionX)
                                        .addComponent(jTextFieldAngularPositionX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabelAngularPositionY)
                                        .addComponent(jTextFieldAngularPositionY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabelAngularPositionZ)
                                        .addComponent(jTextFieldAngularPositionZ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 0, Short.MAX_VALUE))
                                        .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(4, 4, 4)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /*********************************************************************************************************
     * ActionPerformed - Functions
     ********************************************************************************************************/
    private void jTextFieldLinearPositionXActionPerformed(java.awt.event.ActionEvent evt){}
    private void jTextFieldLinearPositionYActionPerformed(java.awt.event.ActionEvent evt){}
    private void jTextFieldLinearPositionZActionPerformed(java.awt.event.ActionEvent evt){}
    private void jTextFieldAngularPositionXActionPerformed(java.awt.event.ActionEvent evt){}
    private void jTextFieldAngularPositionYActionPerformed(java.awt.event.ActionEvent evt){}
    private void jTextFieldAngularPositionZActionPerformed(java.awt.event.ActionEvent evt){}

    /*********************************************************************************************************
     * jToggleButton0ItemStateChanged
     ********************************************************************************************************/
    private void jToggleButton0ItemStateChanged(java.awt.event.ItemEvent evt) {

        switch (evt.getStateChange()) {
            case 1:
                chasi.registerInstance();
                break;
            case 2:
                break;
        }
    }

    /*********************************************************************************************************
     * jToggleButton1ItemStateChanged
     ********************************************************************************************************/
    private void jToggleButton1ItemStateChanged(java.awt.event.ItemEvent evt) {

        switch (evt.getStateChange()) {
            case 1:
                chasi.startHostComponent();
                break;
            case 2:
                chasi.stopHostComponent();
                break;
        }
    }

    /*********************************************************************************************************
     * Button2 Operations
     ********************************************************************************************************/
    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {}
    private void jToggleButton2StateChanged(javax.swing.event.ChangeEvent evt) {}
    private void jToggleButton2ItemStateChanged(java.awt.event.ItemEvent evt) {

        switch (evt.getStateChange()) {
            case 1:
                jToggleButtonChasi.setText("Stop ARTI Chasi");
                chasi.start();
                break;
            case 2:
                jToggleButtonChasi.setText("Start ARTI Chasi");
                chasi.stop();
                break;
        }
    }

    /*********************************************************************************************************
     * Main function
     *
     * @param args the command line arguments
     ********************************************************************************************************/
    public static void main(String args[]) {

        if(args.length == 1 && (args[0].equals("noGUI"))) // launch application without a GUI
        {
            ChasiDevice chasi = new ChasiDevice();

            System.out.println("Started application without GUI!\n Trying to host I4.0 Component:");
            chasi.startHostComponent();

            System.out.println("\n Trying to register ARTI Chasi:");
            chasi.registerInstance();

            System.out.println("\n Trying to start ARTI Chasi communication:");
            chasi.start();
        }
        else // launch application with a GUI
        {
            /* Set Nimbus look and feel (http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html) */
            try {
                for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                    if ("Nimbus".equals(info.getName())) {
                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
                        break;
                    }
                }
            } catch (ClassNotFoundException ex) {
                java.util.logging.Logger.getLogger(MainChasiDevice.class
                        .getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (InstantiationException ex) {
                java.util.logging.Logger.getLogger(MainChasiDevice.class
                        .getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (IllegalAccessException ex) {
                java.util.logging.Logger.getLogger(MainChasiDevice.class
                        .getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                java.util.logging.Logger.getLogger(MainChasiDevice.class
                        .getName()).log(java.util.logging.Level.SEVERE, null, ex);
            }

            /* Create and display the form */
            java.awt.EventQueue.invokeLater(new Runnable() {
                public void run() {
                    new MainChasiDevice().setVisible(true);
                }
            });
        }
    }
}
